### PR TITLE
PR for Discord Update

### PR DESCRIPTION
**Pull request by pazuzu156**
With a new Discord update comes breaks to the design. I've just fixed these breaks. Images provided

Before:
31689260_10155859945494051_8970371593804972032_n

After:
screenshot_1

Any other changes you need me to make before you accept the PR, just let me know.

### CODE REVIEW

**Comment by chrisduerr** [comment]
I don't really use Discord much anymore and because of that would propose the removal of the theme from this repository.

I'm probably gonna remove the undead-discord.css file from this repository. I can link to your fork of this repository in the Discord section of the readme. If you want to create a different repository just for the Discord theme, please let me know and I'll link to that one.

Once you have provided me with a URL I'll remove the theme from this repository.

**Comment by pazuzu156** [comment]
Okay then, that'll work. I'll remove all the other theme files from the repo since I don't ever work on them. I'll leave the repo as a fork so anyone who bothers looking knows the original author. I'll go ahead and close the pull request as well.

**Comment by pazuzu156** [comment]
@chrisduerr Issues and pull requests posed a problem when attempting to open either in a fork, so I've mirrored the repo into a new one and will be deleting the forked one. The URL you can use in your readme would point to https://github.com/pazuzu156/undead-discord I've also linked to this repo as the original repository, so it can still be easily found.

**Comment by pazuzu156** [comment]
@TUSK3N Please use the link in the above comment to make an issue request on that repo

**Comment by chrisduerr** [comment]
You can allow Issues/PRs in the settings of your Github project even if it is a fork, the default is just to disable this.

I'll update the link in the README to the new repository though, it's probably gonna be easier to maintain like this anyways.

And don't worry too much about giving me credit, as long as the source remains open and contributions are accpeted you can do whatever you want with the code and the name. If you want to change the license, that's fine by me, but you'd probably have to get permission from the other contributors first.

**Comment by pazuzu156** [comment]
Yup, I could enable issues. However, pull requests force redirect to this repository. If there's a way to fix that, Idk what it is xD

**Pull request closed without merging**
