### PR TITLE
User profile/popup and invite links update

### PR DESCRIPTION
**Pull request by pazuzu156**
User profile boxes and popups were updated, so I added those to the css. Invite links were also changed, so I added those too.

Screenshots: Before
invites_before
user_popup_playing_before
user_profile_playing_before
user_profile_before

Screenshots: After
invites_after
user_popup_playing_after
user_profile_playing_after
user_profile_after

If you want me to change anything else before a merge, let me know

### CODE REVIEW

**Comment by chrisduerr** [comment]
Okay, before looking at the code, here are some visual changes I would like to see:
#### Invites:
The borders of both the "Joined" button and the invite are still Discord's colors. I would set the button border to primary background and remove the invite border completely. But feel free to play around with other combinations.

The "Join" button itself is still green. This should probably be changed to the background color. And hovering can then either change opacity a bit or use the secondary background color with a border.

#### Small profiles:
These look good to go. I'd accept that. But if you want to spend the time, please make the user profile pictures squares again. I've looked at the code and all you should need to do is remove a mask.

#### Big profiles:
The mask is an issue with this too. Another thing are the borders again. The borders around the buttons and the border separating "Note" and links should all use the secondary background color.

**Comment by pazuzu156** [comment]
Alright. When I get the chance I'll make the changes. I'll also play around a bit and see what you think. I'll do my best to stay with the overall theme

**Comment by pazuzu156** [comment]
Updated the profile boxes and the invite boxes.

Profiles
small_user_profile
large_user_profile

Invite boxes
invite_boxes

The first join button is default. The red one is when hovered. If you don't like that, let me know

**Comment by pazuzu156** [comment]
Actually, looking at how you did buttons before (from the settings page) I reworked that to match. Maybe you'll like that better

big_profile_request
big_profile_request_hover
invite_boxes

**Comment by chrisduerr** [comment]
I'd reverse the button so it normally is bg but only border when hovered. Except for that everything looks good visually!

The code looks good too, if the windows border works without `!important`, I'll merge this as soon as the button is inversed.

**Comment by pazuzu156** [comment]
Sorry it's taken so long to get that changed. Buttons are reversed as requested. What do you mean the windows border? I have no border around the window. If you're talking about the new Windows title bar, then the border placed there is not using `!important` <- check line 298 in my raw commit

**Comment by chrisduerr** [comment]
Yeah that's what I'm talking about. Its not using important and I can't verify that it still works because I don't run windows. So please make sure it does work or just add important to be sure.

**Comment by pazuzu156** [comment]
Ohhh okay I got ya. Thankfully I run both xD It works fine without the use of `!important` since there is no border style to begin with. The border isn't `required` but it makes the title bar distinct from the rest of the window

title_no_border
vs
title_border

This style means nothing on Linux since there isn't a default title bar. At least there isn't with Xfce and i3

\- EDIT -
If you find it pointless, I'll just remove it for PRs

**Pull request merged**
